[package]
name = "blueshift_vault"
version = "0.1.0"
edition = "2021"

[dependencies]
pinocchio = { version = "0.10.2", features = ["cpi"] }
pinocchio-system = "0.5.0"

[lib]
crate-type = ["lib", "cdylib"]
