[package]
name = "blueshift_escrow"
version = "0.1.0"
edition = "2021"

[dependencies]
pinocchio = "0.6.0"
pinocchio-associated-token-account = "0.1.0"
pinocchio-system = "0.3.0"
pinocchio-token = "0.3.0"

[lib]
crate-type = ["cdylib"]

[profile.release]
overflow-checks = true